version: '3'

services:
  web:
    image: iahspeu-api:titan-latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./_secrets:/app/utilities/data"

    command: npm start
    ports:
      - "9016:80"
    restart: unless-stopped
    container_name: sh-subscriptions-api
    environment:
      APP_PORT: 80
      APP_HOSTNAME: '0.0.0.0'
      APP_ENVIRONMENT: 'prod'
      CORS_WHITELIST: '["http://localhost:4200", "https://stagedhomes.com", "https://www.stagedhomes.com", "staging.stagedhomes.com"]'
      DB_HOST: 'hyrule.civzmo75fwsi.us-west-2.rds.amazonaws.com'
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: 'shmain'
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
